Repository nanoframework/nanoFramework.m2mqtt, pull requests merged in 2019-07, with the labels that each got.

#1 Improve MqttNetworkChannel constructor
  M2Mqtt/Net/MqttNetworkChannel.cs
Labels: enhancement

#2 Fix client authentication
  M2Mqtt/MqttClient.cs
  M2Mqtt/Net/MqttNetworkChannel.cs
Labels: enhancement

#3 Improve handling of SslProtocols
  M2Mqtt/Net/MqttNetworkChannel.cs
Labels: bug

#4 Intelisense improvements
  M2Mqtt/Exceptions/MqttClientException.cs
  M2Mqtt/Exceptions/MqttConnectionException.cs
  M2Mqtt/MqttSettings.cs
  M2Mqtt/Net/MqttNetworkChannel.cs
Labels: Type: documentation, Type: enhancement

#5 Update readme.txt
  M2Mqtt/readme.txt
Labels: Type: documentation

#6 Add client certificate support
  M2Mqtt/Net/MqttNetworkChannel.cs
  M2Mqtt/nanoFramework.M2Mqtt.nfproj
  M2Mqtt/packages.config
Labels: Type: dependencies
