Repository nanoframework/nanoFramework.m2mqtt, pull requests merged in 2022-10, with the labels that each got.

#288 Add packages.lock
  M2Mqtt/nanoFramework.M2Mqtt.nfproj
  M2Mqtt/packages.lock.json
  Tests/MessageUnitTests/MessageUnitTests.nfproj
  Tests/MessageUnitTests/packages.lock.json
Labels: Area: Config-and-Build

#289 Fix unit tests
  .runsettings
  Tests/MessageUnitTests/MessageUnitTests.nfproj
  nanoFramework.M2Mqtt.sln
Labels: Type: Unit Tests

#286 Replace `TickCount` with official `TickCount64`
  M2Mqtt/Messages/MqttMsgContext.cs
  M2Mqtt/MqttClient.cs
  M2Mqtt/Nanoframework/Environment.cs
  M2Mqtt/nanoFramework.M2Mqtt.nfproj
Labels: Type: bug, Breaking-Change

#296 Revert "Replace `TickCount` with official `TickCount64` (#286)"
  M2Mqtt/Messages/MqttMsgContext.cs
  M2Mqtt/MqttClient.cs
  M2Mqtt/Nanoframework/Environment.cs
  M2Mqtt/nanoFramework.M2Mqtt.nfproj
Labels: Type: bug
